version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - node -v
      - npm install
      - node -v
  build:
    commands:
      - npm test
  post_build:
    commands:
      - mkdir -p .out
      - aws cloudformation package --template-file template.yml --s3-bucket ${STAGING_BUCKET_PREFIX}-${AWS_REGION} --output-template-file .out/template.yml
      - aws s3 cp .out/template.yml s3://${STAGING_BUCKET_PREFIX}-${AWS_REGION}/template.yml
