version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - pip install aws-sam-cli
      - npm install
  build:
    commands:
      - npm test
      - sam --version
      - mkdir .out
      - sam package --template-file template.yml --s3-bucket ${STAGING_BUCKET_PREFIX}-${AWS_REGION} --output-template-file .out/packaged.yaml
      - export VERSION=`node bin/getVersion.js`
      - aws s3 cp .out/packaged.yaml s3://${STAGING_BUCKET_PREFIX}-${AWS_REGION}/${VERSION}/template.yml
  post_build:
    commands:
      - export VERSION=`node bin/getVersion.js`
      - sam publish --template .out/packaged.yaml --semantic-version ${VERSION} --region ${AWS_REGION}
      - sam publish --template .out/packaged.yaml --semantic-version ${VERSION} --region us-east-1