AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Create pipeline-dashboard application."
Parameters:
  PipelinePattern:
    Description: "The pattern of pipeline names to allow access to describe.  Recommended value: *"
    Type: String

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mechanicalrock-pipeline-dashboard
    Description: Simple dashboard built for viewing pipeline metrics in AWS. Fork of https://github.com/stelligent/pipeline-dashboard Shows trends of pipeline metrics over time
    Author: Mechanical Rock
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ["metrics", "pipeline", "dora"]
    HomePageUrl: https://github.com/MechanicalRock/pipeline-dashboard
    SemanticVersion: 1.0.3
    SourceCodeUrl: https://github.com/MechanicalRock/pipeline-dashboard
Resources:
  PipelineDashboardEventHandler:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: Create CloudWatch metrics from CodePipeline events
      Handler: index.handlePipelineEvent
      Runtime: nodejs12.x
      CodeUri: .
      Events:
        PipelineEventRule:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.codepipeline"
              detail-type:
                - "CodePipeline Pipeline Execution State Change"
                - "CodePipeline Stage Execution State Change"
                - "CodePipeline Action Execution State Change"
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - CodePipelineReadOnlyPolicy:
            PipelineName: !Ref PipelinePattern
  PipelineDashboardGenerator:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: Build CloudWatch dashboard from CloudWatch metrics
      Handler: index.generateDashboard
      Runtime: nodejs12.x
      CodeUri: .
      Timeout: 60
      Events:
        DashboardEventRule:
          Type: Schedule
          Properties:
            Schedule: "cron(*/5 * * * ? *)"
      Policies:
        - CloudWatchDashboardPolicy: {}
  PipelineDashboardTrendGenerator:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: Build CloudWatch Trend dashboard from CloudWatch metrics
      Handler: index.generateDashboardTrend
      Runtime: nodejs12.x
      CodeUri: .
      Timeout: 60
      Events:
        DashboardEventRule:
          Type: Schedule
          Properties:
            Schedule: "cron(*/5 * * * ? *)"
      Policies:
        - CloudWatchDashboardPolicy: {}
